### ISSUE TITLE
javascript encryption

### ISSUE THREAD

**Issue by patrickp-at-work** [Mike96Angelo/Secure-Storage#1]
Hello,

I am not a frontend engineer but I regularly work with colleagues who are frontend experts and per my understanding, it is not recommended to use JavaScript based crypto for a number of reasons: https://stackoverflow.com/a/24677597/1746685
Assuming that your code would run in a browser out there, how would the key remain secret?
I think it would be necessary to drop some words of precaution in the documentation, explaining what are the limitations of your lib, and which precautions would help users to stay secure.

Edit: There are people on the web who have put a lot of thought into why local storage is inherently insecure: https://dev.to/rdegges/please-stop-using-local-storage-1i04 If the intent of the encryption is to avoid all the described attack vectors, then it better be super secure :)

Best
Patrick

**Comment by virgolee2209** [comment]
> 
> 
> Hello,
> 
> I am not a frontend engineer but I regularly work with colleagues who are frontend experts and per my understanding, it is not recommended to use JavaScript based crypto for a number of reasons: https://stackoverflow.com/a/24677597/1746685
> Assuming that your code would run in a browser out there, how would the key remain secret?
> I think it would be necessary to drop some words of precaution in the documentation, explaining what are the limitations of your lib, and which precautions would help users to stay secure.
> 
> Edit: There are people on the web who have put a lot of thought into why local storage is inherently insecure: https://dev.to/rdegges/please-stop-using-local-storage-1i04 If the intent of the encryption is to avoid all the described attack vectors, then it better be super secure :)
> 
> Best
> Patrick

I was looking at this to get an idea how to secure my data in clients as well and I think the same after I read the instruction. There is no good way to hide the private key anyway so even though this can encrypt the data but everyone can decrypt it (the key is not secure as fasr as my understanding goes).

**Comment by Mike96Angelo** [comment]
Thanks for your feedback. 

I have updated the to [README.md](https://github.com/Mike96Angelo/Secure-Storage/blob/master/README.md) with some precautions about storing Secret Keys.

Secret Keys should be **a)** user inputed or **b)** obtained through a secure authenticated request. Do **NOT** ship your Secret Key in your code.

**Comment by uwejan** [comment]
@Mike96Angelo Say the `key` is 1 time coming from the server, how are we supposed to use it?

**Comment by Mike96Angelo** [comment]
@uwejan The browser doesn't have a secure way to store a secret-key, so that not something I would try to do.
